# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  NEAT-benchmarks:
    dependencies:
    - base
    - NEAT
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Machine Learning
description: NEAT is a new Haskeleton package.
executables:
  NEAT:
    dependencies:
    - base
    - NEAT
    - MonadRandom
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: nionita/NEAT
library:
  dependencies:
  - base
  - array
  - containers
  - MonadRandom
  source-dirs: library
license: MIT
maintainer: Niculae Ionita
name: NEAT
synopsis: This package implements Neuro Evolution through Augmenting Topologies
description: The NEAT method by Kenneth O. Stanley and Risto Miikkulainen is a method
        of evolving neuronal networks that tend to be minimal, folowing an evolutionary
        approach. See the paper in http://mitpress.mit.edu/journals.
tests:
  NEAT-test-suite:
    dependencies:
    - base
    - NEAT
    - tasty
    - tasty-hspec
    - containers
    - MonadRandom
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
